### ISSUE TITLE
ETL9 information

### ISSUE THREAD

**Issue by pyjavo** [Nippon2019/Handwritten-Japanese-Recognition#4]
Hi @Nippon2019 
I loved your article, great work. Thanks for sharing.

I am training some neural networks with just Kanji characters and I'm block creating the `modify_kanji` method for ETL9. (as you did with ETL8). Do you happen to know where are the hiragana located inside ETL9 to delete them? [Similar to what you did in /Kanji/modify_kanj.py#L18](https://github.com/Nippon2019/Handwritten-Japanese-Recognition/blob/master/Kanji/modify_kanj.py#L18)
I couldn't find the information in the [original source](http://etlcdb.db.aist.go.jp/specification-of-etl-9).

I really appreciate your help

**Comment by Nippon2019** [comment]
Hi @pyjavo 
Thanks for reading my article!

Yeah that was actually one of the reasons I decided not to train on ETL9 in the end, because I didn't know the exact content of it and I didn't want to spend time figuring it out. Looking back at the original source though, it says that あ has data 'A.HI', so I'm guessing that the Hiraganas in ETL9 would have data ending in '.HI'. Something similar to what I did in [/Hiragana/read_hira.py#L21](https://github.com/Nippon2019/Handwritten-Japanese-Recognition/blob/master/Hiragana/read_hira.py#L21) and changing the ```if b'.HIRA'``` to ```if not b'.HI'``` might work. 

I hope that helps! lmk if you have any other questions, I'd be happy to help!
